AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact
Style/HashSyntax:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
Layout/LineLength:
  Exclude:
    - bin/**/*
Lint/EmptyBlock:
  Exclude:
    - test/factories/**/*.rb
